// <auto-generated />
namespace EstoqueEntityModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Ciacao_Banco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ciacao_Banco));
        
        string IMigrationMetadata.Id
        {
            get { return "201912222037445_Ciacao_Banco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
